version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /actions/*/*
    assignees:
      - muleyuck
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      day: saturday
      timezone: Asia/Tokyo
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
