name: audit-rust

on:
  workflow_call:

permissions: {}
defaults:
  run:
    shell: bash

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install cargo-audit
        run: cargo install --locked cargo-audit

      - name: Run cargo audit
        run: cargo audit
